services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: optigo-docmost_docmost_1
      APP_PORT: 3010

  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "http://localhost:3010"
      APP_SECRET: "TW3kJSO4HMdwq8Vlc0L8ZRCIZxtO4R"
      DATABASE_URL: "postgresql://docmost:HpKm6jar9T@db:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3010:3010"
    restart: unless-stopped
    volumes:
      - /docker/docmost/data:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: HpKm6jar9T
    restart: unless-stopped
    volumes:
      - /docker/docmost/db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - /docker/docmost/redis_data:/data
